# Generated by Django 3.0.3 on 2020-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200411_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
